kind: ConfigMap
apiVersion: v1
metadata:
  name: hello-tomcat-s2ienvironment
data:
  env: |
    #MAVEN_CLEAR_REPO=true
    MAVEN_S2I_GOALS=clean package sonar:sonar
    MAVEN_ARGS_APPEND=-Dsonar.projectKey=${{ values.appName }} -Dsonar.projectName='${{ values.appName }}' -Dsonar.host.url=${{ values.sonarqubeHost }}  -Dsonar.token=${{ values.sonarqubeToken }}
    #
    # MAVEN REPO TO PUSH ARTIFACTS
    #
    #MAVEN_REPOS=nexus
    #NEXUS_MAVEN_REPO_ID=nexus
    #NEXUS_MAVEN_REPO_URL=${env.NEXUS_HOST}
    #NEXUS_MAVEN_REPO_USERNAME=${env.NEXUS_USERNAME}
    #NEXUS_MAVEN_REPO_PASSWORD=${env.NEXUS_PASSWORD}
    #
    # MAVEN MIRROR
    #
    #NEXUS_HOST=http://nexus3:8081
    #NEXUS_USERNAME=myuser
    #NEXUS_PASSWORD=mypass
    #MAVEN_MIRRORS=dev
    #DEV_MAVEN_MIRROR_ID=nexus
    #DEV_MAVEN_MIRROR_URL=${env.NEXUS_HOST}/repository/maven-central/
    #DEV_MAVEN_MIRROR_OF=<![CDATA[*]]>