apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    backstage.io/kubernetes-id: ${{ values.appName }}
  name: hello-tomcat
spec:
  template:
    metadata:
      labels:
        backstage.io/kubernetes-id: ${{ values.appName }}
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/${{ values.namespace }}-dev/hello-tomcat:stable
          name: hello-tomcat
          imagePullPolicy: Always
