apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-tomcat
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/${{ values.namespace }}/hello-tomcat
          name: hello-tomcat
          imagePullPolicy: Always
