apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    backstage.io/kubernetes-id: ${{ values.appName }}
  name: hello-tomcat
spec:
  template:
    metadata:
      labels:
        backstage.io/kubernetes-id: ${{ values.appName }}
    spec:
      containers:
        - name: hello-tomcat
          imagePullPolicy: Always
