---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ${{ values.appName }}-el
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: commit-binding
      interceptors:
        - params:
            - name: filter
              value: 'body["ref"].contains("main") && header.match("X-GitHub-Event", "push")'
            - name: overlays
              value: null
          ref:
            name: cel
      name: commit-trig
      template:
        ref: ${{ values.appName }}-run-build
    - bindings:
        - kind: TriggerBinding
          ref: tag-binding-preprod
      interceptors:
        - params:
            - name: filter
              value: 'header.match("X-GitHub-Event", "push")'
            - name: overlays
              value:
                - expression: 'body.ref.split(''/'')[2]'
                  key: tag_version
          ref:
            kind: ClusterInterceptor
            name: cel
      name: tag-trig-preprod
      template:
        ref: ${{ values.appName }}-run-promote
    - bindings:
        - kind: TriggerBinding
          ref: tag-binding-prod
      interceptors:
        - params:
            - name: filter
              value: 'header.match("X-GitHub-Event", "release")'
          ref:
            kind: ClusterInterceptor
            name: cel
      name: tag-trig-prod
      template:
        ref: ${{ values.appName }}-run-promote