apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- build-pipeline.yaml
- build-configmap.yaml
- buildah_s2i_task.yaml
- generate_sbom_task.yaml
- vulnerability_sbom_task.yaml
- hello_tomcat_is.yaml
- jws_is.yaml

patches:
- deployment.yaml
