apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- pipeline-build.yaml
- build-configmap.yaml
- buildah_s2i_task.yaml
- generate_sbom_task.yaml
- vulnerability_sbom_task.yaml
- hello_tomcat_is.yaml
- jws_is.yaml
- task-rekor-signed-provenance.yaml
- el.yaml
- git_secrets.yaml
- route-el.yaml
- triggerbinding-commit.yaml
- triggertemplate-build.yaml
- triggerbinding-tag-preprod.yaml
- triggertemplate-promote.yaml
- pipeline-promote.yaml

patchesStrategicMerge:
- deployment.yaml
