apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ${{ values.appName }}-build
  labels:
    type: pipeline
    backstage.io/kubernetes-id: ${{ values.appName }}
spec:
  workspaces:
    - name: src
    - name: env
    - name: secureenv
    - name: artifacts
    - name: empty
    - name: ssh
    - name: gitops
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: src
      params:
        - name: url
          value: "https://github.com/${{ values.orgName }}/${{ values.appName }}.git"
        - name: revision
          value: "${{ values.defaultBranch }}"
        - name: deleteExisting
          value: "true"
    - name: build
      taskRef:
        name: buildah-s2i
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: src
        - name: environment
          workspace: env
        - name: secureenvironment
          workspace: secureenv
        - name: artifacts
          workspace: artifacts
      params:
        - name: BUILDER_IMAGE
          value: "image-registry.openshift-image-registry.svc:5000/${{ values.namespace }}/jws60-openjdk17-openshift-rhel8"
        - name: TLSVERIFY
          value: "false"
        - name: OUTPUT_IMAGE
          value: "image-registry.openshift-image-registry.svc:5000/${{ values.namespace }}/hello-tomcat"
        - name: PATH_CONTEXT
          value: "."
    - name: generate-sbom
      taskRef:
        name: generate-sbom
      workspaces:
        - name: source
          workspace: src
      runAfter:
        - build
      params:
        - name: IMAGETOSCAN
          value: "$(tasks.build.results.IMAGE_URL)@$(tasks.build.results.IMAGE_DIGEST)"
        - name: SBOMFILE
          value: "$(workspaces.source.path)/tomcat-sbom.cdx"
        - name: TLSVERIFY
          value: "false"
        - name: OUTPUT_IMAGE
          value: "image-registry.openshift-image-registry.svc:5000/${{ values.namespace }}/hello-tomcat"
    - name: vuln-scan
      taskRef:
        name: vulnerability-sbom
      workspaces:
        - name: source
          workspace: src
      runAfter:
        - generate-sbom
      params:
        - name: SBOM
          value: "$(workspaces.source.path)/tomcat-sbom.cdx"
    - name: query-rekor-signed-provenance
      params:
        - name: imageDigest
          value: $(tasks.generate-sbom.results.IMAGE_DIGEST)
      taskRef:
        kind: Task
        name: rekor-signed-provenance
      runAfter:
      - vuln-scan
    - name: clone-gitops
      taskRef:
        name: git-clone
        kind: ClusterTask
      runAfter:
        - query-rekor-signed-provenance
      workspaces:
        - name: output
          workspace: gitops
        - name: ssh-directory
          workspace: ssh
      params:
        - name: url
          value: "git@github.com:${{ values.orgName }}/${{ values.appName }}-config.git"
        - name: revision
          value: "${{ values.defaultBranch }}"
        - name: deleteExisting
          value: "true"
    - name: edit-deployment
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - clone-gitops
      workspaces:
        - name: manifest-dir
          workspace: gitops
      params:
        - name: SCRIPT
          value: |
            cd $(workspaces.manifest-dir.path)/overlay/dev

            cat <<EOF > deployment.yaml
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: hello-tomcat
            spec:
              template:
                spec:
                  containers:
                    - image: $(tasks.generate-sbom.results.IMAGE_URL)@$(tasks.generate-sbom.results.IMAGE_DIGEST)
                      name: hello-tomcat
                      imagePullPolicy: Always
            EOF
    - name: git-commit
      taskRef:
        name: git-cli
        kind: ClusterTask
      runAfter:
        - edit-deployment
      workspaces:
        - name: source
          workspace: gitops
        - name: ssh-directory
          workspace: ssh
      params:
        - name: GIT_SCRIPT
          value: |
            git config --global --add safe.directory $(workspaces.source.path)
            
            git config --global user.email "giuseppe.magnotta@gmail.com"
  
            git config --global user.name "TEKTON CI"

            git pull --quiet origin HEAD:${{ values.defaultBranch }}

            git add $(workspaces.source.path)/overlay/dev/deployment.yaml

            git commit -m "Deploy new image in dev $(tasks.generate-sbom.results.IMAGE_URL)@$(tasks.generate-sbom.results.IMAGE_DIGEST)"
            
            git push --quiet origin HEAD:${{ values.defaultBranch }}