apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ${{ values.appName }}-promote
  labels:
    type: pipeline
    backstage.io/kubernetes-id: ${{ values.appName }}
spec:
  params:
    - name: source-image-hash
      type: string
    - name: dest-image-tag
      type: string
  tasks:
    - name: copy-image
      params:
        - name: srcImageURL
          value: 'docker://image-registry.openshift-image-registry.svc:5000/${{ values.namespace }}/hello-tomcat@sha256:$(params.source-image-hash)'
        - name: destImageURL
          value: 'docker://quay.io/gmagnotta/hello-tomcat:$(params.dest-image-tag)'
        - name: srcTLSverify
          value: 'false'
        - name: destTLSverify
          value: 'false'
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: images-url
    - name: copy-att
      params:
        - name: srcImageURL
          value: 'docker://image-registry.openshift-image-registry.svc:5000/${{ values.namespace }}/hello-tomcat:sha256-$(params.source-image-hash).att'
        - name: destImageURL
          value: 'docker://quay.io/gmagnotta/hello-tomcat:sha256-$(params.source-image-hash).att'
        - name: srcTLSverify
          value: 'false'
        - name: destTLSverify
          value: 'false'
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: images-url
    - name: copy-sig
      params:
        - name: srcImageURL
          value: 'docker://image-registry.openshift-image-registry.svc:5000/${{ values.namespace }}/hello-tomcat:sha256-$(params.source-image-hash).sig'
        - name: destImageURL
          value: 'docker://quay.io/gmagnotta/hello-tomcat:sha256-$(params.source-image-hash).sig'
        - name: srcTLSverify
          value: 'false'
        - name: destTLSverify
          value: 'false'
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: images-url
    - name: clone-gitops
      taskRef:
        name: git-clone
        kind: ClusterTask
      runAfter:
        - copy-image
        - copy-att
        - copy-sig
      workspaces:
        - name: output
          workspace: gitops
        - name: ssh-directory
          workspace: ssh
      params:
        - name: url
          value: "git@github.com:${{ values.orgName }}/${{ values.appName }}-gitops.git"
        - name: revision
          value: "${{ values.defaultBranch }}"
        - name: deleteExisting
          value: "true"
    - name: edit-deployment
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - clone-gitops
      workspaces:
        - name: manifest-dir
          workspace: gitops
      params:
        - name: SCRIPT
          value: |
            mkdir -p $(workspaces.manifest-dir.path)/overlay/test

            cd $(workspaces.manifest-dir.path)/overlay/test

            cat <<EOF > deployment.yaml
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: hello-tomcat
            spec:
              template:
                spec:
                  containers:
                    - image: quay.io/gmagnotta/hello-tomcat:$(params.dest-image-tag)
                      name: hello-tomcat
                      imagePullPolicy: Always
            EOF
    - name: git-commit
      taskRef:
        name: git-cli
        kind: ClusterTask
      runAfter:
        - edit-deployment
      workspaces:
        - name: source
          workspace: gitops
        - name: ssh-directory
          workspace: ssh
      params:
        - name: GIT_SCRIPT
          value: |
            git config --global --add safe.directory $(workspaces.source.path)
            
            git config --global user.email "giuseppe.magnotta@gmail.com"
  
            git config --global user.name "Tekton CI"

            git pull --quiet origin HEAD:${{ values.defaultBranch }}

            git add $(workspaces.source.path)/overlay/test/deployment.yaml

            git commit -m "Deploy new image in test quay.io/gmagnotta/hello-tomcat:$(params.dest-image-tag)"
            
            git push --quiet origin HEAD:${{ values.defaultBranch }}
  workspaces:
    - name: images-url
    - name: ssh
    - name: gitops
