apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: listener
  name: el-listener
  namespace: "{{ project }}"
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-listener
    weight: 100