apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: push-trigger-template
  namespace: "{{ project }}"
spec:
  params:
  - name: git-repository-url
    description: The git repository url
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: hello-tomcat-
    spec:
      pipelineRef:
        name: hello-tomcat
      workspaces:
        - name: src
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
              volumeMode: Filesystem
            status: {}
        - configMap:
            name: hello-tomcat-s2ienvironment
          name: env
        - emptyDir: {}
          name: secureenv
        - name: artifacts
          emptyDir: {}