apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tag-binding-preprod
spec:
  params:
    - name: source-image-hash
      value: $(extensions.source_image_hash)
    - name: dest-image-tag
      value: $(extensions.dest_image_tag)