---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ${{ values.appName }}-run-promote
spec:
  params:
    - name: source-image-hash
      description: The source image to promote
    - name: dest-image-tag
      description: The dest image to tag
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: $(uid)
        labels:
          backstage.io/kubernetes-id: ${{ values.appName }}
      spec:
        params:
          - name: source-image-hash
            value: $(tt.params.source-image-hash)
          - name: dest-image-tag
            value: $(tt.params.dest-image-tag)
        pipelineRef:
          name: ${{ values.appName }}-promote
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: images-url
            emptyDir: {}
          - name: ssh
            secret:
              secretName: git-secrets
          - name: gitops
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi