apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: quarkus-echo
  labels:
    app: quarkus-echo
    backstage.io/kubernetes-id: ${{ values.appName }}
spec:
  to:
    kind: Service
    name: quarkus-echo
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None